text = input('Digite algo: ')
print('O seu texto é do tipo: {}'.format(type(text)))
print('É alfanumérico: {}'.format(text.isalnum()))
print('É alfabético: {}'.format(text.isalpha()))
print('É um numero: {}'.format(text.isnumeric()))
print('Só tem espaços: {}'.format(text.isspace()))
print('Está capitalizada: {}'.format(text.istitle()))
print('Está em maiúsculas: {}'.format(text.isupper()))
print('Está em minúsculas: {}'.format(text.islower()))